In [1]:
import datacube
from datacube.storage import masking
from datacube import Datacube
from datetime import datetime
from skimage import exposure

#load requiered modules #load r 
import numpy as np
import rasterio
from rasterio import features

import xarray as xr
import pandas as pd
import geopandas as gpd
from geopandas import GeoSeries, GeoDataFrame

import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [2]:
from sklearn.datasets import make_classification

In [3]:
#define fuction for loading part of a bulti band GIF 

def load_gfif_full(file_name, x=1):


    dataset = rasterio.open(file_name) #open using Raterio
    {i: dtype for i, dtype in zip(dataset.indexes, dataset.dtypes)}
    data_array = dataset.read(x) #read selected band into np array
    data_xr = xr.DataArray(data_array) #turn into Xr array for fuctionality #Now don't need xr yet
    return(data_xr) #return np array into program

In [4]:
panda_training= pd.read_csv('/g/data/u46/users/ck9738/Datasets/ML_for_smad_green/shapefiles_for_train/ncas_truthed_one.csv',
                            usecols=(1,2,3,4),nrows=483400)
# open the data we are going to use for training and testing as a dataframe
panda_training

        class         1         2         3
0           0  0.003713  0.508305  0.498965
1           0  0.005193  0.577651  0.553511
2           0  0.005193  0.577651  0.553511
3           0  0.005193  0.577651  0.553511
4           1  0.009352  0.661980  0.591735
5           1  0.009352  0.661980  0.591735
6           1  0.004694  0.668501  0.624123
7           1  0.004694  0.668501  0.624123
8           1  0.004694  0.668501  0.624123
9           1  0.002938  0.536924  0.518079
10          0  0.002938  0.536924  0.518079
11          0  0.001762  0.453553  0.448216
12          0  0.001762  0.453553  0.448216
13          1  0.001762  0.453553  0.448216
14          1  0.001549  0.534163  0.523585
15          1  0.001549  0.534163  0.523585
16          1  0.003268  0.604188  0.576471
17          1  0.003268  0.604188  0.576471
18          1  0.003268  0.604188  0.576471
19          1  0.013730  0.751296  0.630658
20          1  0.013730  0.751296  0.630658
21          1  0.007026  0.625832  0.556511
22          1  0.007026  0.625832  0.556511
23          0  0.007026  0.625832  0.556511
24          0  0.003663  0.538398  0.511915
25          0  0.003663  0.538398  0.511915
26          0  0.005111  0.597519  0.536905
27          1  0.005111  0.597519  0.536905
28          1  0.005111  0.597519  0.536905
29          1  0.007953  0.647011  0.568906
...       ...       ...       ...       ...
483370      0  0.021485  0.599439  0.531101
483371      0  0.021485  0.599439  0.531101
483372      0  0.047829  0.628990  0.559766
483373      0  0.047829  0.628990  0.559766
483374      0  0.049238  0.625567  0.560763
483375      0  0.049238  0.625567  0.560763
483376      0  0.049238  0.625567  0.560763
483377      0  0.045753  0.593214  0.533316
483378      0  0.045753  0.593214  0.533316
483379      0  0.043397  0.579008  0.520599
483380      0  0.043397  0.579008  0.520599
483381      0  0.043397  0.579008  0.520599
483382      0  0.049134  0.623278  0.533630
483383      0  0.049134  0.623278  0.533630
483384      0  0.047496  0.644044  0.540842
483385      0  0.047496  0.644044  0.540842
483386      0  0.047496  0.644044  0.540842
483387      0  0.049050  0.598314  0.540597
483388      0  0.049050  0.598314  0.540597
483389      0  0.027456  0.585388  0.517691
483390      0  0.027456  0.585388  0.517691
483391      0  0.027456  0.585388  0.517691
483392      0  0.011957  0.591527  0.554814
483393      0  0.011957  0.591527  0.554814
483394      0  0.021395  0.548539  0.519761
483395      0  0.021395  0.548539  0.519761
483396      0  0.021395  0.548539  0.519761
483397      0  0.015470  0.547483  0.511933
483398      0  0.015470  0.547483  0.511933
483399      0  0.012789  0.530214  0.506570

[483400 rows x 4 columns]

In [6]:
smad_list = panda_training['1'].values.tolist()
max_list = panda_training['2'].values.tolist()
min_list = panda_training['3'].values.tolist()
classification = panda_training['class'].values.tolist()
#create array of features to use in classifier and array of the classification answer
how_many = len(smad_list)
how_many

features = []

for i in range(how_many):
    features.append((smad_list[i],max_list[i],min_list[i]))
features
features_array = np.asarray(features)

classification_array = np.asarray(classification)

In [7]:
features_array

array([[0.00371332, 0.50830454, 0.4989653 ],
       [0.0051931 , 0.57765085, 0.5535112 ],
       [0.0051931 , 0.57765085, 0.5535112 ],
       ...,
       [0.0154695 , 0.54748315, 0.5119329 ],
       [0.0154695 , 0.54748315, 0.5119329 ],
       [0.01278939, 0.5302142 , 0.5065701 ]])

In [8]:
classification_array

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
#Split the feature array and the classification answer arrays into kn chuncks for the kfold validation. here K = 4

K=4

kt1,kt2,kt3,kt4, = np.split(features_array, 4)
kc1,kc2,kc3,kc4, = np.split(classification_array, 4)

In [21]:
#define classifier

#pick your method
#classify = LinearSVC(random_state=0)
#classify = RandomForestClassifier(bootstrap=False, max_depth=10, random_state=0)
classify = ExtraTreesClassifier(bootstrap=False, random_state=0)

In [22]:
#define classifily fuction 

def train_and_test(test_f,train_f,train_c):
    """    takes data in chunks, puts the training data back into a stack to train and putputs a 
    boolian array of the test cassification
    test_f = test data to be classified. 2D array size[sample_n, features_n]
    
    train_f = list of arrays each 2D array size[sample_n, features_n].
            each is one K chunck of the total data set, to be used to train. should equal total data - 1k.
    
    train_C = list of arrays each 1D array size[sample_n]. boolean values equal to classification answer
            each is one K chunck of the total data set, to be used to train. should equal total data - 1k.
            
    returns = 1D array size[sample_n]. boolean values equal to classification answer. size equal to test_f
    """
    train_f = np.concatenate(train_f,axis=0)
    train_c = np.concatenate(train_c,axis=0)
    classify.fit(train_f,train_c)#fit the moddle to the training data
    print(classify.feature_importances_)
    results=classify.predict(test_f)#run predict on test data
    return(results)

In [23]:
restult_one = train_and_test(kt1,[kt2,kt3,kt4],[kc2,kc3,kc4])
restult_two = train_and_test(kt2,[kt1,kt3,kt4],[kc1,kc3,kc4])
restult_three = train_and_test(kt3,[kt1,kt2,kt4],[kc1,kc2,kc4])
restult_four = train_and_test(kt4,[kt1,kt2,kt3],[kc1,kc2,kc3])
#compleate test for each K chunk
join_results = np.concatenate((restult_one,restult_two,restult_three,restult_four),axis=0)
join_results#join results back together

[0.48307403 0.20149277 0.31543319]
[0.51241246 0.18841789 0.29916965]
[0.43671874 0.19017083 0.37311043]
[0.35341666 0.27173101 0.37485233]

array([0, 1, 1, ..., 0, 0, 0])

In [24]:
classify.get_params

<bound method BaseEstimator.get_params of ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)>

In [25]:
panda_training['test_result']=pd.Series(join_results, index=panda_training.index)
#add results as new column to panda data frame
panda_training

        class         1         2         3  test_result
0           0  0.003713  0.508305  0.498965            0
1           0  0.005193  0.577651  0.553511            1
2           0  0.005193  0.577651  0.553511            1
3           0  0.005193  0.577651  0.553511            1
4           1  0.009352  0.661980  0.591735            1
5           1  0.009352  0.661980  0.591735            1
6           1  0.004694  0.668501  0.624123            1
7           1  0.004694  0.668501  0.624123            1
8           1  0.004694  0.668501  0.624123            1
9           1  0.002938  0.536924  0.518079            1
10          0  0.002938  0.536924  0.518079            1
11          0  0.001762  0.453553  0.448216            0
12          0  0.001762  0.453553  0.448216            0
13          1  0.001762  0.453553  0.448216            0
14          1  0.001549  0.534163  0.523585            1
15          1  0.001549  0.534163  0.523585            1
16          1  0.003268  0.604188  0.576471            1
17          1  0.003268  0.604188  0.576471            1
18          1  0.003268  0.604188  0.576471            1
19          1  0.013730  0.751296  0.630658            1
20          1  0.013730  0.751296  0.630658            1
21          1  0.007026  0.625832  0.556511            1
22          1  0.007026  0.625832  0.556511            1
23          0  0.007026  0.625832  0.556511            1
24          0  0.003663  0.538398  0.511915            1
25          0  0.003663  0.538398  0.511915            1
26          0  0.005111  0.597519  0.536905            1
27          1  0.005111  0.597519  0.536905            1
28          1  0.005111  0.597519  0.536905            1
29          1  0.007953  0.647011  0.568906            1
...       ...       ...       ...       ...          ...
483370      0  0.021485  0.599439  0.531101            0
483371      0  0.021485  0.599439  0.531101            0
483372      0  0.047829  0.628990  0.559766            0
483373      0  0.047829  0.628990  0.559766            0
483374      0  0.049238  0.625567  0.560763            0
483375      0  0.049238  0.625567  0.560763            0
483376      0  0.049238  0.625567  0.560763            0
483377      0  0.045753  0.593214  0.533316            0
483378      0  0.045753  0.593214  0.533316            0
483379      0  0.043397  0.579008  0.520599            0
483380      0  0.043397  0.579008  0.520599            0
483381      0  0.043397  0.579008  0.520599            0
483382      0  0.049134  0.623278  0.533630            0
483383      0  0.049134  0.623278  0.533630            0
483384      0  0.047496  0.644044  0.540842            0
483385      0  0.047496  0.644044  0.540842            0
483386      0  0.047496  0.644044  0.540842            0
483387      0  0.049050  0.598314  0.540597            0
483388      0  0.049050  0.598314  0.540597            0
483389      0  0.027456  0.585388  0.517691            0
483390      0  0.027456  0.585388  0.517691            0
483391      0  0.027456  0.585388  0.517691            0
483392      0  0.011957  0.591527  0.554814            0
483393      0  0.011957  0.591527  0.554814            0
483394      0  0.021395  0.548539  0.519761            0
483395      0  0.021395  0.548539  0.519761            0
483396      0  0.021395  0.548539  0.519761            0
483397      0  0.015470  0.547483  0.511933            0
483398      0  0.015470  0.547483  0.511933            0
483399      0  0.012789  0.530214  0.506570            0

[483400 rows x 5 columns]

In [26]:
number_correct_total = np.count_nonzero(join_results)
average_correct = (number_correct_total/K)
percent_correct = (average_correct/(483400/K))*100
print(number_correct_total, average_correct, percent_correct)

160587 40146.75 33.22031443938767

In [27]:
panda_training.to_csv('/g/data/u46/users/ck9738/Datasets/ML_for_smad_green/kfold_results_ncas_truthed.csv')
#save data as CSV to analyse in XL